version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - run:
          name: Install Wine for Electron builder
          command: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt install wine32
